name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 13 */1 * *'

permissions:
  contents: write

env:
  TOKENZ: ${{ secrets.TOKENZ }}

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - run: |
          go run *.go \
            --token ${{ secrets.TOKENZ }} \
            --preset indonesia \
            --amount 6000 \
            --consider 6000 \
            --output json \
            --file ./data
      - run: ls -al

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node code.js

      - run: ls -al
      
      - name: push generated file
        run: |
          d=$(date +"%Y-%m-%d")
          git config --global user.name 'Theo Browne'
          git config --global user.email 't3dotgg@users.noreply.github.com'
          git pull
          ls -al
          git add indogithubers.json
          git commit -am "update indogithubers data - $d"
          git push
